/* ============================================================
   SERVICE WORKER — generated by tools/build-sw.py. Do not edit by hand.

   Gives Layla the whole app offline (about 2.0 MB, including every
   approved phoneme recording) and makes updates land predictably.

   Strategy:
   - navigation  -> network first, cache as fallback. A new deploy is picked
                    up immediately when online; the app still opens on a
                    plane or in a car when not.
   - static      -> cache first. Scripts and styles carry ?v=20260905092141, so a
                    new build simply asks for different URLs and can never
                    pair a new script with a stale one.
   - old caches  -> deleted on activate.
   ============================================================ */
'use strict';

const VERSION = '20260905092141';
const CACHE = 'layla-kingdom-' + VERSION;

/* Everything needed to run with no network at all. */
const PRECACHE = [
  './app.js',
  './audio/phonemes/a.mp3',
  './audio/phonemes/ai.mp3',
  './audio/phonemes/air.mp3',
  './audio/phonemes/ar.mp3',
  './audio/phonemes/b.mp3',
  './audio/phonemes/ch.mp3',
  './audio/phonemes/d.mp3',
  './audio/phonemes/e_short.mp3',
  './audio/phonemes/ear.mp3',
  './audio/phonemes/ee.mp3',
  './audio/phonemes/er.mp3',
  './audio/phonemes/f.mp3',
  './audio/phonemes/g.mp3',
  './audio/phonemes/h.mp3',
  './audio/phonemes/i.mp3',
  './audio/phonemes/igh.mp3',
  './audio/phonemes/j.mp3',
  './audio/phonemes/k.mp3',
  './audio/phonemes/l.mp3',
  './audio/phonemes/m.mp3',
  './audio/phonemes/manifest.json',
  './audio/phonemes/n.mp3',
  './audio/phonemes/ng.mp3',
  './audio/phonemes/o_short.mp3',
  './audio/phonemes/oa.mp3',
  './audio/phonemes/oi.mp3',
  './audio/phonemes/oo_long.mp3',
  './audio/phonemes/oo_short.mp3',
  './audio/phonemes/or.mp3',
  './audio/phonemes/ow.mp3',
  './audio/phonemes/p.mp3',
  './audio/phonemes/qu.mp3',
  './audio/phonemes/r.mp3',
  './audio/phonemes/s.mp3',
  './audio/phonemes/sh.mp3',
  './audio/phonemes/t.mp3',
  './audio/phonemes/th_unvoiced.mp3',
  './audio/phonemes/th_voiced.mp3',
  './audio/phonemes/v.mp3',
  './audio/phonemes/w.mp3',
  './audio/phonemes/x.mp3',
  './audio/phonemes/y.mp3',
  './audio/phonemes/z.mp3',
  './audio/voice/another-adventure.mp3',
  './audio/voice/beautiful.mp3',
  './audio/voice/big-first.mp3',
  './audio/voice/blend-together.mp3',
  './audio/voice/bravo.mp3',
  './audio/voice/build-name.mp3',
  './audio/voice/castle-hello.mp3',
  './audio/voice/find-sound.mp3',
  './audio/voice/find-your-name.mp3',
  './audio/voice/first-sound.mp3',
  './audio/voice/found-name.mp3',
  './audio/voice/go-castle.mp3',
  './audio/voice/good-try.mp3',
  './audio/voice/hear-again.mp3',
  './audio/voice/hi-layla.mp3',
  './audio/voice/kitten-free.mp3',
  './audio/voice/kitten-stuck.mp3',
  './audio/voice/land-sleeping.mp3',
  './audio/voice/listen-carefully.mp3',
  './audio/voice/look-unlocked.mp3',
  './audio/voice/match-letters.mp3',
  './audio/voice/missing-letter.mp3',
  './audio/voice/name-spelled.mp3',
  './audio/voice/new-sound.mp3',
  './audio/voice/oops.mp3',
  './audio/voice/paint-fun.mp3',
  './audio/voice/rainbow-help.mp3',
  './audio/voice/rhyme-ask.mp3',
  './audio/voice/sentence-win.mp3',
  './audio/voice/sound-it-out.mp3',
  './audio/voice/sticker-hello.mp3',
  './audio/voice/story-help.mp3',
  './audio/voice/trace-ask.mp3',
  './audio/voice/try-it-on.mp3',
  './audio/voice/unicorn-help.mp3',
  './audio/voice/welcome-back.mp3',
  './audio/voice/yes-a.mp3',
  './audio/voice/yes-c.mp3',
  './audio/voice/yes-d.mp3',
  './audio/voice/yes-g.mp3',
  './audio/voice/yes-i.mp3',
  './audio/voice/yes-k.mp3',
  './audio/voice/yes-m.mp3',
  './audio/voice/yes-n.mp3',
  './audio/voice/yes-o.mp3',
  './audio/voice/yes-p.mp3',
  './audio/voice/yes-s.mp3',
  './audio/voice/yes-t.mp3',
  './audio/voice/you-did-it.mp3',
  './audio/voice/you-read-a-word.mp3',
  './audio/words/Sam.mp3',
  './audio/words/am.mp3',
  './audio/words/apple.mp3',
  './audio/words/at.mp3',
  './audio/words/can.mp3',
  './audio/words/cap.mp3',
  './audio/words/cat.mp3',
  './audio/words/dog.mp3',
  './audio/words/gap.mp3',
  './audio/words/igloo.mp3',
  './audio/words/in.mp3',
  './audio/words/it.mp3',
  './audio/words/kite.mp3',
  './audio/words/lion.mp3',
  './audio/words/man.mp3',
  './audio/words/map.mp3',
  './audio/words/mat.mp3',
  './audio/words/moon.mp3',
  './audio/words/mop.mp3',
  './audio/words/net.mp3',
  './audio/words/on.mp3',
  './audio/words/otter.mp3',
  './audio/words/pan.mp3',
  './audio/words/pat.mp3',
  './audio/words/pin.mp3',
  './audio/words/pot.mp3',
  './audio/words/sat.mp3',
  './audio/words/sip.mp3',
  './audio/words/sit.mp3',
  './audio/words/sun.mp3',
  './audio/words/tap.mp3',
  './audio/words/tin.mp3',
  './audio/words/tip.mp3',
  './characters.js',
  './content.js',
  './devtools.js',
  './felt-characters.js',
  './felt-princess.js',
  './feltkit.js',
  './icons/apple-touch-icon.png',
  './icons/icon-192.png',
  './icons/icon-512.png',
  './icons/icon-maskable-512.png',
  './index.html',
  './manifest.json',
  './phonics.js',
  './princess.js',
  './progress.js',
  './runtime.js',
  './styles.css',
  './zone-play.js',
  './zone-reading.js'
];

self.addEventListener('install', (e) => {
  e.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    /* One missing file must not fail the whole install, so add them in
       small batches and tolerate individual failures. */
    for (let i = 0; i < PRECACHE.length; i += 12) {
      const batch = PRECACHE.slice(i, i + 12);
      await Promise.all(batch.map((u) =>
        cache.add(new Request(u, {cache: 'reload'})).catch(() => {})
      ));
    }
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (e) => {
  e.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)));
    await self.clients.claim();
  })());
});

self.addEventListener('message', (e) => {
  if (e.data === 'SKIP_WAITING') self.skipWaiting();
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;

  const url = new URL(req.url);
  const sameOrigin = url.origin === self.location.origin;

  /* The page itself: prefer the network so a deploy is seen at once. */
  if (req.mode === 'navigate') {
    e.respondWith((async () => {
      try {
        const fresh = await fetch(req);
        const cache = await caches.open(CACHE);
        cache.put('./index.html', fresh.clone()).catch(() => {});
        return fresh;
      } catch (err) {
        return (await caches.match('./index.html')) ||
               (await caches.match(req)) ||
               new Response('Offline', {status: 503});
      }
    })());
    return;
  }

  /* Google Fonts: serve from cache, refresh quietly in the background. */
  if (!sameOrigin) {
    e.respondWith((async () => {
      const hit = await caches.match(req);
      const net = fetch(req).then((res) => {
        if (res && res.status === 200) {
          caches.open(CACHE).then((c) => c.put(req, res.clone())).catch(() => {});
        }
        return res;
      }).catch(() => null);
      return hit || (await net) || new Response('', {status: 504});
    })());
    return;
  }

  /* App files and audio: cache first. */
  e.respondWith((async () => {
    const hit = await caches.match(req, {ignoreSearch: false});
    if (hit) return hit;
    try {
      const res = await fetch(req);
      if (res && res.status === 200 && res.type === 'basic') {
        const cache = await caches.open(CACHE);
        cache.put(req, res.clone()).catch(() => {});
      }
      return res;
    } catch (err) {
      /* A versioned asset may have been requested before precache finished;
         fall back to any cached copy regardless of query string. */
      const loose = await caches.match(req, {ignoreSearch: true});
      return loose || new Response('', {status: 504});
    }
  })());
});
