"""Generate sw.js and stamp index.html with a fresh build version.

Run after any change to shipped files:

    python tools/build-sw.py

Two jobs, kept together on purpose so they can never disagree:
  1. rewrite ?v=<stamp> on every local <script>/<link> in index.html
  2. regenerate sw.js with the same stamp and a real list of files to
     precache, so the tablet gets the whole app offline

The stamp is what makes updates land. Old caches are deleted on activate,
and the versioned URLs mean a stale script can never be paired with a new
one -- which is what made an earlier fix look like it had not deployed.
"""
import os
import re
import time

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))

# Everything the app actually serves. tools/, .claude/ and _retired/ are not shipped.
SKIP_DIRS = {"tools", ".claude", ".git", "_retired", "node_modules", "__pycache__"}
SKIP_FILES = {"package.json", "package-lock.json", ".gitignore", "sw.js"}
SHIP_EXT = {".html", ".js", ".css", ".json", ".mp3", ".png", ".svg", ".webp", ".woff2"}


def shipped_files():
    out = []
    for base, dirs, files in os.walk(ROOT):
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS and not d.startswith(".")]
        for f in files:
            if f in SKIP_FILES:
                continue
            if os.path.splitext(f)[1].lower() not in SHIP_EXT:
                continue
            rel = os.path.relpath(os.path.join(base, f), ROOT).replace("\\", "/")
            if rel.startswith("tools/") or "_retired/" in rel:
                continue
            out.append("./" + rel)
    return sorted(out)


def stamp_index(stamp):
    p = os.path.join(ROOT, "index.html")
    s = open(p, encoding="utf-8").read()
    s = re.sub(r'(\.js|\.css)(\?v=[0-9]+)?"', lambda m: m.group(1) + "?v=" + stamp + '"', s)
    open(p, "w", encoding="utf-8").write(s)
    return len(re.findall(r"\?v=" + stamp, s))


SW_TEMPLATE = '''/* ============================================================
   SERVICE WORKER — generated by tools/build-sw.py. Do not edit by hand.

   Gives Layla the whole app offline (about %(mb).1f MB, including every
   approved phoneme recording) and makes updates land predictably.

   Strategy:
   - navigation  -> network first, cache as fallback. A new deploy is picked
                    up immediately when online; the app still opens on a
                    plane or in a car when not.
   - static      -> cache first. Scripts and styles carry ?v=%(stamp)s, so a
                    new build simply asks for different URLs and can never
                    pair a new script with a stale one.
   - old caches  -> deleted on activate.
   ============================================================ */
'use strict';

const VERSION = '%(stamp)s';
const CACHE = 'layla-kingdom-' + VERSION;

/* Everything needed to run with no network at all. */
const PRECACHE = %(files)s;

self.addEventListener('install', (e) => {
  e.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    /* One missing file must not fail the whole install, so add them in
       small batches and tolerate individual failures. */
    for (let i = 0; i < PRECACHE.length; i += 12) {
      const batch = PRECACHE.slice(i, i + 12);
      await Promise.all(batch.map((u) =>
        cache.add(new Request(u, {cache: 'reload'})).catch(() => {})
      ));
    }
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (e) => {
  e.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)));
    await self.clients.claim();
  })());
});

self.addEventListener('message', (e) => {
  if (e.data === 'SKIP_WAITING') self.skipWaiting();
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;

  const url = new URL(req.url);
  const sameOrigin = url.origin === self.location.origin;

  /* The page itself: prefer the network so a deploy is seen at once. */
  if (req.mode === 'navigate') {
    e.respondWith((async () => {
      try {
        const fresh = await fetch(req);
        const cache = await caches.open(CACHE);
        cache.put('./index.html', fresh.clone()).catch(() => {});
        return fresh;
      } catch (err) {
        return (await caches.match('./index.html')) ||
               (await caches.match(req)) ||
               new Response('Offline', {status: 503});
      }
    })());
    return;
  }

  /* Google Fonts: serve from cache, refresh quietly in the background. */
  if (!sameOrigin) {
    e.respondWith((async () => {
      const hit = await caches.match(req);
      const net = fetch(req).then((res) => {
        if (res && res.status === 200) {
          caches.open(CACHE).then((c) => c.put(req, res.clone())).catch(() => {});
        }
        return res;
      }).catch(() => null);
      return hit || (await net) || new Response('', {status: 504});
    })());
    return;
  }

  /* App files and audio: cache first. */
  e.respondWith((async () => {
    const hit = await caches.match(req, {ignoreSearch: false});
    if (hit) return hit;
    try {
      const res = await fetch(req);
      if (res && res.status === 200 && res.type === 'basic') {
        const cache = await caches.open(CACHE);
        cache.put(req, res.clone()).catch(() => {});
      }
      return res;
    } catch (err) {
      /* A versioned asset may have been requested before precache finished;
         fall back to any cached copy regardless of query string. */
      const loose = await caches.match(req, {ignoreSearch: true});
      return loose || new Response('', {status: 504});
    }
  })());
});
'''


def main():
    stamp = time.strftime("%Y%m%d%H%M%S")
    files = shipped_files()
    total = sum(os.path.getsize(os.path.join(ROOT, f[2:])) for f in files)

    n = stamp_index(stamp)

    body = "[\n" + ",\n".join("  '%s'" % f for f in files) + "\n]"
    sw = SW_TEMPLATE % {"stamp": stamp, "files": body, "mb": total / 1048576.0}
    open(os.path.join(ROOT, "sw.js"), "w", encoding="utf-8", newline="\n").write(sw)

    print("  build stamp   : %s" % stamp)
    print("  index.html    : %d versioned refs" % n)
    print("  sw.js         : %d files precached (%.1f MB)" % (len(files), total / 1048576.0))


if __name__ == "__main__":
    main()
